language: julia
os:
  - linux
  - osx
julia:
  - 0.7-beta
  - nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'import Pkg; Pkg.clone(pwd()); Pkg.build("AverageShiftedHistograms"); Pkg.test("AverageShiftedHistograms"; coverage=true)'
after_success:
  - julia -e 'import Pkg; Pkg.add("Documenter")'
  - julia -e 'import Pkg; cd(Pkg.dir("AverageShiftedHistograms")); include(joinpath("docs", "make.jl"))'
  - julia -e 'import Pkg; cd(Pkg.dir("AverageShiftedHistograms")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Coveralls.process_folder())'
