name = "AverageShiftedHistograms"
uuid = "77b51b56-6f8f-5c3a-9cb4-d71f9594ea6e"
version = "0.8.9"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[compat]
RecipesBase = "0.7, 0.8, 1.0, 1.1"
StatsBase = "0.32, 0.33, 0.34"
UnicodePlots = "1.1, 2.0, 2.1, 2.2, 2.3, 2.4, 3"
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
